export const COMMON_CONSTS = {
  SIGN_UP: 'Sign up',
  LOG_IN: 'Log in',
  YOUR_PICK_OF_RIDES_AT: 'Your Pick of rides at low prices',
  LOW_PRICES: 'low prices',
  HOW_DO_YOU_WANT_TO: 'How do you want to',
  LOG_INQ: 'Log in?',
  SIGN_UPQ: 'Sign up?',
  NOT_A_MEMBER_YET: 'Not a member yet?',
  ALREADY_A_MEMBER: 'Already a member?',
  SIGN_UP_WITH_EMAIL: 'Sign up with email',
  CONTINUE_WITH_EMAIL: 'Continue with email',
  X: 'X',
  ARROW: '>',
  WHATS_YOUR_EMAIL: "What's your email",
  AND_PASSWORDQ: 'and password?',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password',
  BACK_ARROW: '<-',
  TIME: 'Time',
  ROUTE: 'Route',
  DURATION: 'Duration',
  DISTANCE: 'Distance',
  EMAIL_REGEX: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/,
  WHATS_YOUR_EMAILQ: "What's your email?",
  ENTER_VALID_EMAIL: 'Enter valid email',
  WHATS_YOUR_NAMEQ: "What's your name?",
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  WHATS_YOUR_DATE_OF: "What's your date of",
  BIRTHQ: 'birth?',
  DATE_MONTH_YEAR: 'dd/mm/yyyy',
  DMY_REGEX: /^(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012])[\/\-]\d{4}$/,
  HOW_WOULD_YOU_LIKE: 'How would you like',
  TO_BE_ADDRESSED: 'to be adddressed?',
  MISS_OR_MADAM: 'Miss / Madam',
  SIR: 'Sir',
  ADD_STOPOVERS_TO_GET_MORE_PASSENGERS: 'Add stops to get more passengers',
  PASSENGER: 'passenger',
  RATHER_NOT_TO_SAY: "I'd rather not say",
  DEFINE_YOUR: 'Define your',
  PASSWORDS: 'password',
  STOPOVER: 'StopOver',
  AT_WHAT_TIME_WILL_YOU_PICK_PASSENGERS_UP:
    'At what time will you pick passengers up?',
  IT_MUST_HAVE_ATLEAST_EIGHT_CHARACTERS_ONE:
    'It must have at least 8 characters, 1',
  LETTER_ONE_NUMBER_AND_ONE_SPECIAL_CHARACTER:
    'letter, 1 number and 1 special character',
  PASSWORD_REGEX:
    /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
  PASSWORD_IS_NOT_VALID: 'Password is not valid',
  SEARCH: 'Search',
  WHEN_ARE_YOU_GOING: 'When are you',
  GOING: 'going?',
  NUMBER_OF_SEATS: 'Number of seats to',
  BOOK: 'book',
  EDIT_INFO: 'Edit info',
  DELETE_VEHICLE: 'Delete Vehicle',
  INBOX: 'Inbox',
  DELETING_A_CAR_FROM_YOUR_PROFILE_MIGHT_MAKE_IT_HARDER:
    'Deleting a car from your profile might make it harder for passengers to find you at the meeting point.',
  LEAVING_FROM: 'Leaving from',
  NO_MESSAGES_RIGHT_NOW:
    'No messages right now. Book or offer a ride to contact someone.',
  GOING_TO: 'Going to',
  TODAY: 'Today',
  PLEASE_VERIFY_YOUR: 'Please verify your',
  MOBILE_NUMBER: 'mobile number',
  I_WILL_DO_IT_LATER: "I'll do it later",
  YOUR_FUTURE_TRAVEL_PLANS_WILL_APPEAR_HERE:
    'Your future travel plans will appear here.',
  FIND_THE_PERFECT_RIDE_FROM:
    'Find the perfect ride from thousands of destinations, or publish to share your travel costs.',
  ABOUT_YOU: 'About you',
  ACCOUNT: 'Account',
  OTP: 'OTP',
  VERIFY: 'Verify',
  VERIFY_OTP: 'Verify Otp',
  ADD_CITY: 'Add city',
  EDIT_PROFILE_PICTURE: 'Edit profile picture',
  EDIT_PERSONAL_DETAILS: 'Edit personal details',
  VERIFY_YOUR_PROFILE: 'Verify your profile',
  VERIFY_MY_ID: 'Verify my ID',
  CONFIRM_EMAIL: 'Confirm email',
  CONFIRM_PHONE_NUMBER: 'Confirm phone number',
  ADD_MINI_BIO: 'Add mini bio',
  ADD_MY_PREFERENCES: 'Add my preferences',
  VEHICLES: 'Vehicles',
  ADD_VEHICLE: 'Add Vehicle',
  RATING: 'Rating',
  NOTIFICATION_EMAIL_AND_SMS: 'Notifications, email & SMS',
  CHANGE_PASSWORD: 'Change password',
  POSTAL_ADDRESS: 'Postal address',
  AVAILABLE_FUNDS: 'Available funds',
  BANK_DETAILS: 'Bank details',
  PAYMENT_AND_REFUNDS: 'Payment & refunds',
  HELP: 'Help',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  DATA_PROTECTION: 'Data protection',
  LICENSES: 'Licenses',
  LOG_OUT: 'Log out',
  NINE_ONE: '(+91)',
  MOBILE_PHONE: 'Mobile phone',
  ENTER_THE_CODE_WEHAVE: "Enter the code we've",
  JUST_SENT_YOU_BY_SMS: 'just sent you by SMS',
  RESEND_CODE: 'Resend code',
  FOUR_DIGIT_CODE: '4-digit code',
  MOBILE_REGEX: /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/,
  ENTER_VALID_DOB: 'Enter valid dob eg: 25/09/2002',
  NAME_REGEX: /^[a-zA-z]+$/,
  NAME_WARN: 'Name can only contain letters',
  NEWCOMER: 'Newcomer',
  GENDER: 'Gender',
  DATE_OF_BIRTH: 'Date of birth',
  EMAIL_ADDRESS: 'Email Address',
  ADD_PHONE_NUMBER: 'Add phone number',
  PERSONAL_DETAILS: 'Personal Details',
  MALE: 'Male',
  FEMALE: 'Female',
  WHATS_YOUR_FIRST: "What's your first",
  NAMEQ: 'name?',
  SAVE: 'Save',
  ERROR_WHILE_UPDATING: 'Error while updating',
  WHAT_IS_YOUR_LAST: 'What is your last',
  WHAT_WOULD_YOU_LIKE: 'What would you like',
  OTHER_MEMBERS_TO: 'other members to',
  KNOW_ABOUT_YOUQ: 'know about you?',
  ERROR_BIO: 'Your mini bio must be min. 10 words',
  WHAT_IS_YOUR_LICENSE: 'What is your license',
  PLATE_NUMBERQ: 'plate number?',
  I_DONOT_KNOW_MY_LICENSE_PLATE: "I don't know my license plate",
  WHATS_YOUR_VEHICLES: "What's your vehicle's",
  BRANDQ: 'brand?',
  TRAVEL_PREFERENCES: 'Travel Preferences',
  CHATTINESS: 'Chattiness',
  MUSIC: 'Music',
  SMOKING: 'Smoking',
  PETS: 'Pets',
  IAM_CHATTY_WHEN_I_FEEL_COMFORTABLE: "I'm chatty when I feel comfortable",
  I_LOVE_TO_CHAT: 'I love to chat',
  IM_THE_QUITE_TYPE: "I'm the quite type",
  ITS_ALL_ABOUT_PLAYLIST: "It's all about the playlist",
  I_LL_JAM_DEPENDING_ON_THE_MOOD: "I'll jam depending on the mood",
  SILENCE_IS_GOLDEN: 'Silence is golden',
  I_AM_FINE_WITH_SMOKING: "I'm fine with smoking",
  CIGARETTE_BREAKS_OUTSIDE_THE_CAR_ARE_OK:
    'Cigarette breaksoutside the car are ok',
  PLEASE_NO_SMOKING_IN_THE_CAR: 'Please, no smoking in the car',
  PETS_WELCOME_WOOFA: 'Pets welcome. woof!',
  I_LL_TRAVEL_WITH_PETS_DEPENDING_ON_THE_ANIMALS:
    "I'll travel with pets depending on the animal",
  SORRY_NOT_A_PET_PERSON: 'Sorry, not a pet person',
  LEFT_ARROW: '<',
  USE_CURRENT_LOCATION: 'Use current location',
  PICK_UP: 'Pick-up',
  ENTER_THE_FULL_ADDRESS: 'Enter the full address',
  DROP_OFF: 'Drop-off',
  COUNTRY: 'Country',
  INDIA: 'India',
  VEHICLE_BRAND: 'Vehicle brand',
  VEHICLE_NAME: 'Vehicle name',
  ENTER_VEHICLE_DETAILS: 'Enter vehicle details',
  VEHICLE_TYPE: 'Vehicle type',
  VEHICLE_COLOR: 'Vehicle color',
  VEHICLE_MODEL_YEAR: 'Vehicle model year',
  NUMBER_PLATE: 'EX-514-SD',
  I_DO_NOT_KNOW_MY_LICENSE_PLATE: "I don't know my license plate",
  PLEASE_ENTER_THE: 'Please enter the',
  EMAIL_YOU_SIGNED_UP: 'email you signed up',
  WITH: 'with',
  SUBMIT: 'Submit',
  CHOOSE_PROFILE_PICTURE: 'Choose your profile',
  PICTURE: 'picture',
  TAKE_A_PICTURE: 'Take a picture',
  CHOOSE_A_PICTURE: 'Choose a picture',
  PLATE_ERROR: 'should contain atleast 8 charectors and atmost 12',
  ERROR: 'ERROR',
  THINK_COMFORT_KEEP_THE_MIDDLE_SEAT_EMPTY:
    'Think comfort, keep the middle seat empty!',
  YES_SURE: 'Yes, sure!',
  SET_THE_PRICE_PER_SEAT: 'Set the price per seat',
  CAN_PASSENGER_BOOK_INSTANTLY: 'Can passengers book instantly?',
  NO_ILL_SQEEZE_IN_THREE: "No, I'll squeeze in 3",
  NO_ILL_REPLY_TO_EACH_REQUEST_MYSELF: "No, I'll reply to each request myself",
  RS: '₹',
  VEHICLE_ERROR: 'Please add vehicle first to publish your ride',
  MIN_PRICE: 'min price: ',
  NETWORK_ERROR:
    'Network error: make sure you are connected to stable internet',
  MAX_PRICE: 'max price',
  ANYTHING_TO_ADD_ABOUT_YOUR_RIDE: 'Anything to add about your ride?',
  PUBLISH: 'Publish',
  EXAMPLE:
    'Example: "I\'m a student at Delhi University, and I often visit friends in Jaipur. I love photography and rock music."',
};
