export const COMMON_CONSTS = {
  SIGN_UP: 'Sign up',
  LOG_IN: 'Log in',
  YOUR_PICK_OF_RIDES_AT: 'Your Pick of rides at',
  LOW_PRICES: 'low prices',
  HOW_DO_YOU_WANT_TO: 'How do you want to',
  LOG_INQ: 'Log in?',
  SIGN_UPQ: 'Sign up?',
  NOT_A_MEMBER_YET: 'Not a member yet?',
  ALREADY_A_MEMBER: 'Already a member?',
  SIGN_UP_WITH_EMAIL: 'Sign up with email',
  CONTINUE_WITH_EMAIL: 'Continue with email',
  X: 'X',
  ARROW: '>',
  WHATS_YOUR_EMAIL: "What's your email",
  AND_PASSWORDQ: 'and password?',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password',
  BACK_ARROW: '<-',
  EMAIL_REGEX: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/,
  WHATS_YOUR_EMAILQ: "What's your email?",
  ENTER_VALID_EMAIL: 'Enter valid email',
  WHATS_YOUR_NAMEQ: "What's your name?",
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  WHATS_YOUR_DATE_OF: "What's your date of",
  BIRTHQ: 'birth?',
  DATE_MONTH_YEAR: 'dd/mm/yyyy',
  DMY_REGEX: /^(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012])[\/\-]\d{4}$/,
  HOW_WOULD_YOU_LIKE: 'How would you like',
  TO_BE_ADDRESSED: 'to be adddressed?',
  MISS_OR_MADAM: 'Miss / Madam',
  SIR: 'Sir',
  RATHER_NOT_TO_SAY: "I'd rather not say",
  DEFINE_YOUR: 'Define your',
  PASSWORDS: 'password',
  IT_MUST_HAVE_ATLEAST_EIGHT_CHARACTERS_ONE:
    'It must have at least 8 characters, 1',
  LETTER_ONE_NUMBER_AND_ONE_SPECIAL_CHARACTER:
    'letter, 1 number and 1 special character',
  PASSWORD_REGEX:
    /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
  PASSWORD_IS_NOT_VALID: 'Password is not valid',
  SEARCH: 'Search',
  WHEN_ARE_YOU_GOING: 'When are you',
  GOING: 'going?',
  NUMBER_OF_SEATS: 'Number of seats to',
  BOOK: 'book',
  LEAVING_FROM: 'Leaving from',
  GOING_TO: 'Going to',
  TODAY: 'Today',
  PLEASE_VERIFY_YOUR: 'Please verify your',
  MOBILE_NUMBER: 'mobile number',
  I_WILL_DO_IT_LATER: "I'll do it later",
  ABOUT_YOU: 'About you',
  ACCOUNT: 'Account',
  EDIT_PROFILE_PICTURE: 'Edit profile picture',
  EDIT_PERSONAL_DETAILS: 'Edit personal details',
  VERIFY_YOUR_PROFILE: 'Verify your profile',
  VERIFY_MY_ID: 'Verify my ID',
  CONFIRM_EMAIL: 'Confirm email',
  CONFIRM_PHONE_NUMBER: 'Confirm phone number',
  ADD_MINI_BIO: 'Add mini bio',
  ADD_MY_PREFERENCES: 'Add my preferences',
  VEHICLES: 'Vehicles',
  ADD_VEHICLE: 'Add Vehicle',
  RATING: 'Rating',
  NOTIFICATION_EMAIL_AND_SMS: 'Notifications, email & SMS',
  CHANGE_PASSWORD: 'Change password',
  POSTAL_ADDRESS: 'Postal address',
  AVAILABLE_FUNDS: 'Available funds',
  BANK_DETAILS: 'Bank details',
  PAYMENT_AND_REFUNDS: 'Payment & refunds',
  HELP: 'Help',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  DATA_PROTECTION: 'Data protection',
  LICENSES: 'Licenses',
  LOG_OUT: 'Log out',
  NINE_ONE: '(+91)',
  MOBILE_PHONE: 'Mobile phone',
  ENTER_THE_CODE_WEHAVE: "Enter the code we've",
  JUST_SENT_YOU_BY_SMS: 'just sent you by SMS',
  RESEND_CODE: 'Resend code',
  FOUR_DIGIT_CODE: '4-digit code',
  MOBILE_REGEX: /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/,
  ENTER_VALID_DOB: 'Enter valid dob eg: 25/09/2002',
  NAME_REGEX: /^[a-zA-z]+$/,
  NAME_WARN: 'Name can only contain letters',
  NEWCOMER: 'Newcomer',
  GENDER: 'Gender',
  DATE_OF_BIRTH: 'Date of birth',
  EMAIL_ADDRESS: 'Email Address',
  ADD_PHONE_NUMBER: 'Add phone number',
  PERSONAL_DETAILS: 'Personal Details',
  MALE: 'Male',
  FEMALE: 'Female',
  WHATS_YOUR_FIRST: "What's your first",
  NAMEQ: 'name?',
  SAVE: 'Save',
  ERROR_WHILE_UPDATING: 'Error while updating',
};
