export const COMMON_CONSTS = {
  SIGN_UP: 'Sign up',
  LOG_IN: 'Log in',
  YOUR_PICK_OF_RIDES_AT: 'Your Pick of rides at',
  LOW_PRICES: 'low prices',
  HOW_DO_YOU_WANT_TO: 'How do you want to',
  LOG_INQ: 'Log in?',
  SIGN_UPQ: 'Sign up?',
  NOT_A_MEMBER_YET: 'Not a member yet?',
  ALREADY_A_MEMBER: 'Already a member?',
  SIGN_UP_WITH_EMAIL: 'Sign up with email',
  CONTINUE_WITH_EMAIL: 'Continue with email',
  X: 'X',
  ARROW: '>',
  WHATS_YOUR_EMAIL: "What's your email",
  AND_PASSWORDQ: 'and password?',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  FORGOT_PASSWORD: 'Forgot Password',
  BACK_ARROW: '<-',
  EMAIL_REGEX: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/,
  WHATS_YOUR_EMAILQ: "What's your email?",
  ENTER_VALID_EMAIL: 'Enter valid email',
  WHATS_YOUR_NAMEQ: "What's your name?",
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  WHATS_YOUR_DATE_OF: "What's your date of",
  BIRTHQ: 'birth?',
  DATE_MONTH_YEAR: 'dd/mm/yyyy',
  DMY_REGEX: /^(0?[1-9]|[12][0-9]|3[01])[\/\-](0?[1-9]|1[012])[\/\-]\d{4}$/,
  HOW_WOULD_YOU_LIKE: 'How would you like',
  TO_BE_ADDRESSED: 'to be adddressed?',
  MISS_OR_MADAM: 'Miss / Madam',
  SIR: 'Sir',
  RATHER_NOT_TO_SAY: "I'd rather not say",
  DEFINE_YOUR: 'Define your',
  PASSWORDS: 'password',
  IT_MUST_HAVE_ATLEAST_EIGHT_CHARACTERS_ONE:
    'It must have at least 8 characters, 1',
  LETTER_ONE_NUMBER_AND_ONE_SPECIAL_CHARACTER:
    'letter, 1 number and 1 special character',
  PASSWORD_REGEX:
    /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
  PASSWORD_IS_NOT_VALID: 'Password is not valid',
  SEARCH: 'Search',
  WHEN_ARE_YOU_GOING: 'When are you',
  GOING: 'going?',
  NUMBER_OF_SEATS: 'Number of seats to',
  BOOK: 'book',
  LEAVING_FROM: 'Leaving from',
  GOING_TO: 'Going to',
  TODAY: 'Today',
};
